name: insurance_app_py311
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy>=1.24,<1.26
  - pandas>=2.2,<2.3
  - scipy>=1.11,<1.12
  - scikit-learn>=1.6,<1.8
  - xgboost>=1.7,<1.8
  - lightgbm>=4.5,<4.7
  - category_encoders>=2.8,<2.9
  - joblib>=1.3,<1.4
  - python-dateutil>=2.8.2
  - pytz>=2020.1
  - tzdata>=2022.7
  - patsy>=0.5.1
  - threadpoolctl>=2.0
  - matplotlib>=3.8,<3.9
  - seaborn>=0.12,<0.13
  - plotly>=6.3,<6.4
  - shap>=0.42,<0.43
  - streamlit>=1.28,<1.29
  - pip:
      - pycaret[full]==3.0.4
